### ISSUE TITLE
Graph Traverse throws exceptions when there are lots of edges on one node

### ISSUE THREAD

**Issue by holocentric-bmsnext** [orientechnologies/OrientDB-NET.binary#149]
When performing a traverse query using 

```database.Query('traverse outE(), inV() from (SELECT FROM Object ORDER BY name  SKIP 0 LIMIT 5000))```
If any of the node contains lots of edges, 

below exception is thrown.
  
 at Orient.Client.Protocol.Response.Receive()
   at Orient.Client.Protocol.Connection.ExecuteOperationInternal(IOperation operation)
   at Orient.Client.Protocol.Connection.ExecuteOperation(IOperation operation)
   at Orient.Client.Protocol.Serializers.RecordCSVSerializer.ParseRidBags(Int32 i, String recordString, ODocument document, String fieldName)
   at Orient.Client.Protocol.Serializers.RecordCSVSerializer.ParseFieldName(Int32 i, String recordString, ODocument document)
   at Orient.Client.Protocol.Serializers.RecordCSVSerializer.Deserialize(String recordString, ODocument document)
   at Orient.Client.Protocol.Operations.Command.Command.ParseDocument(BinaryReader reader)
   at Orient.Client.Protocol.Operations.Command.Command.Response(Response response)
   at Orient.Client.Protocol.Connection.ExecuteOperationInternal(IOperation operation)
   at Orient.Client.Protocol.Connection.ExecuteOperation(IOperation operation)
   at Orient.Client.ODatabase.Query(String sql, String fetchPlan)

**Comment by luigidellaquila** [comment]
This is definitely related to https://github.com/orientechnologies/OrientDB-NET.binary/issues/150, so the proposed solution applies to this issue as well

Thanks

Luigi
