### ISSUE TITLE
{"Cannot write to a BufferedStream while the read buffer is not empty if the underlying stream is not seekable. Ensure that the stream underlying this BufferedStream can seek or avoid interleaving read and write operations on this BufferedStream."}

### ISSUE THREAD

**Issue by nazik** [orientechnologies/OrientDB-NET.binary#6]
I receive the following unhandled exception when run the console application code https://github.com/orientechnologies/OrientDB-NET.binary/blob/master/src/Orient/Orient.Console/Program.cs . Specifically, when the code tries to create a vertex at line 28. I receive the exception when  the code runs against both versions v1.711-snapshot and v2.0-rc1.

Orient.Client.OException was unhandled
  HResult=-2146233088
  Message=Cannot write to a BufferedStream while the read buffer is not empty if the underlying stream is not seekable. Ensure that the stream underlying this BufferedStream can seek or avoid interleaving read and write operations on this BufferedStream.
  Source=Orient.Client
  StackTrace:
       at Orient.Client.Protocol.Connection.Send(Byte[] rawData) in c:\data\training\training\OrientDB-NET.binary-master\src\Orient\Orient.Client\Protocol\Connection.cs:line 265
       at Orient.Client.Protocol.Connection.ExecuteOperation(IOperation operation) in c:\data\training\training\OrientDB-NET.binary-master\src\Orient\Orient.Client\Protocol\Connection.cs:line 104
       at Orient.Client.ORecordCreateVertex.Run() in c:\data\training\training\OrientDB-NET.binary-master\src\Orient\Orient.Client\API\Query\ORecordCreateVertex.cs:line 122
       at Orient.Console.Program.Main(String[] args) in c:\data\training\training\OrientDB-NET.binary-master\src\Orient\Orient.Console\Program.cs:line 33
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by GoorMoon** [comment]
@nazik ,
Could you please check again with latest version from master branch ?

**Comment by nazik** [comment]
Tested the latest version with OrientDB 2.0.2 with no problems.

**Comment by ugavnholt** [comment]
I'm getting this error too with the latest version of the binary driver, and orientdb version 2.0.3
